// Code generated by protoc-gen-go.
// source: UnProtos/Data/Movement.proto
// DO NOT EDIT!

/*
Package UnProtos_Data is a generated protocol buffer package.

It is generated from these files:
	UnProtos/Data/Movement.proto
	UnProtos/Data/Vec3.proto

It has these top-level messages:
	Movement
	Vec3
*/
package UnProtos_Data

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Movement struct {
	// position определяет положение
	Position *Vec3 `protobuf:"bytes,1,opt,name=position" json:"position,omitempty"`
	// motion определяет движение
	Motion *Vec3 `protobuf:"bytes,2,opt,name=motion" json:"motion,omitempty"`
	// angle определяет направление (угол между положительным направленим оси Y и направлением по часовой стрелке)
	Angle float64 `protobuf:"fixed64,3,opt,name=angle" json:"angle,omitempty"`
	// slew определяет поворот (угол по часовой стрелке)
	Slew float64 `protobuf:"fixed64,4,opt,name=slew" json:"slew,omitempty"`
}

func (m *Movement) Reset()                    { *m = Movement{} }
func (m *Movement) String() string            { return proto.CompactTextString(m) }
func (*Movement) ProtoMessage()               {}
func (*Movement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Movement) GetPosition() *Vec3 {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Movement) GetMotion() *Vec3 {
	if m != nil {
		return m.Motion
	}
	return nil
}

func (m *Movement) GetAngle() float64 {
	if m != nil {
		return m.Angle
	}
	return 0
}

func (m *Movement) GetSlew() float64 {
	if m != nil {
		return m.Slew
	}
	return 0
}

func init() {
	proto.RegisterType((*Movement)(nil), "UnProtos.Data.Movement")
}

func init() { proto.RegisterFile("UnProtos/Data/Movement.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x09, 0xcd, 0x0b, 0x28,
	0xca, 0x2f, 0xc9, 0x2f, 0xd6, 0x77, 0x49, 0x2c, 0x49, 0xd4, 0xf7, 0xcd, 0x2f, 0x4b, 0xcd, 0x4d,
	0xcd, 0x2b, 0xd1, 0x2b, 0x00, 0x09, 0x0a, 0xf1, 0xc2, 0x64, 0xf5, 0x40, 0xb2, 0x52, 0x12, 0xa8,
	0x8a, 0xc3, 0x52, 0x93, 0x8d, 0x21, 0x0a, 0x95, 0x26, 0x31, 0x72, 0x71, 0xc0, 0xf4, 0x0a, 0xe9,
	0x73, 0x71, 0x14, 0xe4, 0x17, 0x67, 0x96, 0x64, 0xe6, 0xe7, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x1b, 0x09, 0xeb, 0xa1, 0x18, 0xa4, 0x07, 0xd2, 0x19, 0x04, 0x57, 0x24, 0xa4, 0xcd, 0xc5, 0x96,
	0x9b, 0x0f, 0x56, 0xce, 0x84, 0x5b, 0x39, 0x54, 0x89, 0x90, 0x08, 0x17, 0x6b, 0x62, 0x5e, 0x7a,
	0x4e, 0xaa, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x63, 0x10, 0x84, 0x23, 0x24, 0xc4, 0xc5, 0x52, 0x9c,
	0x93, 0x5a, 0x2e, 0xc1, 0x02, 0x16, 0x04, 0xb3, 0x93, 0xd8, 0xc0, 0x6e, 0x33, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x29, 0x5e, 0x2f, 0x81, 0xe4, 0x00, 0x00, 0x00,
}
