// Code generated by protoc-gen-go.
// source: UnProtos/Messaging/Message.proto
// DO NOT EDIT!

/*
Package UnProtos_Messaging is a generated protocol buffer package.

It is generated from these files:
	UnProtos/Messaging/Message.proto
	UnProtos/Messaging/MessageType.proto

It has these top-level messages:
	Message
*/
package UnProtos_Messaging

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Type MessageType `protobuf:"varint,1,opt,name=type,enum=UnProtos.Messaging.MessageType" json:"type,omitempty"`
	Body []byte      `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_APPLY_CONTROLLER
}

func (m *Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "UnProtos.Messaging.Message")
}

func init() { proto.RegisterFile("UnProtos/Messaging/Message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 120 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x08, 0xcd, 0x0b, 0x28,
	0xca, 0x2f, 0xc9, 0x2f, 0xd6, 0xf7, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0xcf, 0xcc, 0x4b, 0x87, 0xb2,
	0x52, 0xf5, 0x0a, 0x40, 0x12, 0x42, 0x42, 0x30, 0x15, 0x7a, 0x70, 0x15, 0x52, 0x2a, 0xb8, 0x75,
	0x85, 0x54, 0x16, 0x40, 0x75, 0x2a, 0x05, 0x71, 0xb1, 0x43, 0x05, 0x85, 0x8c, 0xb9, 0x58, 0x4a,
	0x2a, 0x0b, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0xf8, 0x8c, 0xe4, 0xf5, 0x30, 0xcd, 0xd4, 0x43,
	0xd2, 0x1f, 0x04, 0x56, 0x2c, 0x24, 0xc4, 0xc5, 0x92, 0x94, 0x9f, 0x52, 0x29, 0xc1, 0xa4, 0xc0,
	0xa8, 0xc1, 0x13, 0x04, 0x66, 0x27, 0xb1, 0x81, 0x8d, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x48, 0xdd, 0x11, 0x80, 0xb8, 0x00, 0x00, 0x00,
}
