// Code generated by protoc-gen-go.
// source: UnProtos/Messaging/Requests/ApplyControllerRequest.proto
// DO NOT EDIT!

/*
Package UnProtos_Messaging_Requests is a generated protocol buffer package.

It is generated from these files:
	UnProtos/Messaging/Requests/ApplyControllerRequest.proto
	UnProtos/Messaging/Requests/GetChankRequest.proto
	UnProtos/Messaging/Requests/GetTerrainRequest.proto

It has these top-level messages:
	ApplyControllerRequest
	GetChunkRequest
	GetTerrainRequest
*/
package UnProtos_Messaging_Requests

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ApplyControllerRequest определяет нажатые клавиши управления
type ApplyControllerRequest struct {
	// клавиши управления
	MoveForward  bool `protobuf:"varint,1,opt,name=move_forward,json=moveForward" json:"move_forward,omitempty"`
	MoveBackward bool `protobuf:"varint,2,opt,name=move_backward,json=moveBackward" json:"move_backward,omitempty"`
	MoveLeft     bool `protobuf:"varint,3,opt,name=move_left,json=moveLeft" json:"move_left,omitempty"`
	MoveRight    bool `protobuf:"varint,4,opt,name=move_right,json=moveRight" json:"move_right,omitempty"`
	RotateLeft   bool `protobuf:"varint,5,opt,name=rotate_left,json=rotateLeft" json:"rotate_left,omitempty"`
	RotateRight  bool `protobuf:"varint,6,opt,name=rotate_right,json=rotateRight" json:"rotate_right,omitempty"`
	// клавиши-модификаторы
	Mods *ApplyControllerRequest_Modifiers `protobuf:"bytes,7,opt,name=mods" json:"mods,omitempty"`
}

func (m *ApplyControllerRequest) Reset()                    { *m = ApplyControllerRequest{} }
func (m *ApplyControllerRequest) String() string            { return proto.CompactTextString(m) }
func (*ApplyControllerRequest) ProtoMessage()               {}
func (*ApplyControllerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ApplyControllerRequest) GetMoveForward() bool {
	if m != nil {
		return m.MoveForward
	}
	return false
}

func (m *ApplyControllerRequest) GetMoveBackward() bool {
	if m != nil {
		return m.MoveBackward
	}
	return false
}

func (m *ApplyControllerRequest) GetMoveLeft() bool {
	if m != nil {
		return m.MoveLeft
	}
	return false
}

func (m *ApplyControllerRequest) GetMoveRight() bool {
	if m != nil {
		return m.MoveRight
	}
	return false
}

func (m *ApplyControllerRequest) GetRotateLeft() bool {
	if m != nil {
		return m.RotateLeft
	}
	return false
}

func (m *ApplyControllerRequest) GetRotateRight() bool {
	if m != nil {
		return m.RotateRight
	}
	return false
}

func (m *ApplyControllerRequest) GetMods() *ApplyControllerRequest_Modifiers {
	if m != nil {
		return m.Mods
	}
	return nil
}

type ApplyControllerRequest_Modifiers struct {
	Shift bool `protobuf:"varint,1,opt,name=shift" json:"shift,omitempty"`
	Ctrl  bool `protobuf:"varint,2,opt,name=ctrl" json:"ctrl,omitempty"`
	Alt   bool `protobuf:"varint,3,opt,name=alt" json:"alt,omitempty"`
	Meta  bool `protobuf:"varint,4,opt,name=meta" json:"meta,omitempty"`
}

func (m *ApplyControllerRequest_Modifiers) Reset()         { *m = ApplyControllerRequest_Modifiers{} }
func (m *ApplyControllerRequest_Modifiers) String() string { return proto.CompactTextString(m) }
func (*ApplyControllerRequest_Modifiers) ProtoMessage()    {}
func (*ApplyControllerRequest_Modifiers) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

func (m *ApplyControllerRequest_Modifiers) GetShift() bool {
	if m != nil {
		return m.Shift
	}
	return false
}

func (m *ApplyControllerRequest_Modifiers) GetCtrl() bool {
	if m != nil {
		return m.Ctrl
	}
	return false
}

func (m *ApplyControllerRequest_Modifiers) GetAlt() bool {
	if m != nil {
		return m.Alt
	}
	return false
}

func (m *ApplyControllerRequest_Modifiers) GetMeta() bool {
	if m != nil {
		return m.Meta
	}
	return false
}

func init() {
	proto.RegisterType((*ApplyControllerRequest)(nil), "UnProtos.Messaging.Requests.ApplyControllerRequest")
	proto.RegisterType((*ApplyControllerRequest_Modifiers)(nil), "UnProtos.Messaging.Requests.ApplyControllerRequest.Modifiers")
}

func init() {
	proto.RegisterFile("UnProtos/Messaging/Requests/ApplyControllerRequest.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x89, 0x49, 0x6b, 0x3b, 0xa9, 0x20, 0x8b, 0x48, 0xb0, 0x88, 0xad, 0x5e, 0x7a, 0x4a,
	0x40, 0x2f, 0x5e, 0x3c, 0xa8, 0xe0, 0xc9, 0x82, 0x06, 0x3c, 0x79, 0x90, 0x6d, 0xb3, 0x49, 0x83,
	0x9b, 0x6c, 0xdc, 0x1d, 0x15, 0xdf, 0xc2, 0x47, 0x96, 0x9d, 0xdd, 0xf4, 0xa4, 0xde, 0x26, 0xdf,
	0xfc, 0xdf, 0x90, 0xfc, 0x81, 0xcb, 0xa7, 0xf6, 0x41, 0x2b, 0x54, 0x26, 0x5b, 0x0a, 0x63, 0x78,
	0x55, 0xb7, 0x55, 0x96, 0x8b, 0xb7, 0x77, 0x61, 0xd0, 0x64, 0xd7, 0x5d, 0x27, 0xbf, 0x6e, 0x55,
	0x8b, 0x5a, 0x49, 0x29, 0xb4, 0xe7, 0x69, 0x67, 0x05, 0x36, 0xed, 0xcd, 0x74, 0x6b, 0xa6, 0xbd,
	0x79, 0xfa, 0x1d, 0xc2, 0xe1, 0xef, 0x36, 0x9b, 0xc3, 0xa4, 0x51, 0x1f, 0xe2, 0xa5, 0x54, 0xfa,
	0x93, 0xeb, 0x22, 0x09, 0x66, 0xc1, 0x62, 0x94, 0xc7, 0x96, 0xdd, 0x39, 0xc4, 0xce, 0x60, 0x8f,
	0x22, 0x2b, 0xbe, 0x7e, 0xa5, 0xcc, 0x0e, 0x65, 0xc8, 0xbb, 0xf1, 0x8c, 0x4d, 0x61, 0x4c, 0x21,
	0x29, 0x4a, 0x4c, 0x42, 0x0a, 0x8c, 0x2c, 0xb8, 0x17, 0x25, 0xb2, 0x63, 0x00, 0x5a, 0xea, 0xba,
	0xda, 0x60, 0x12, 0xd1, 0x96, 0xe2, 0xb9, 0x05, 0xec, 0x04, 0x62, 0xad, 0x90, 0xa3, 0xb7, 0x07,
	0xb4, 0x07, 0x87, 0xc8, 0x9f, 0xc3, 0xc4, 0x07, 0xdc, 0x85, 0xa1, 0x7b, 0x49, 0xc7, 0xdc, 0x8d,
	0x47, 0x88, 0x1a, 0x55, 0x98, 0x64, 0x77, 0x16, 0x2c, 0xe2, 0xf3, 0xab, 0xf4, 0x9f, 0x3a, 0xd2,
	0x3f, 0x8a, 0x5c, 0xaa, 0xa2, 0x2e, 0x6b, 0xa1, 0x4d, 0x4e, 0xa7, 0x8e, 0x9e, 0x61, 0xbc, 0x45,
	0xec, 0x00, 0x06, 0x66, 0x53, 0x97, 0xe8, 0x0b, 0x72, 0x0f, 0x8c, 0x41, 0xb4, 0x46, 0x2d, 0x7d,
	0x23, 0x34, 0xb3, 0x7d, 0x08, 0xb9, 0xec, 0x3b, 0xb0, 0xa3, 0x4d, 0x35, 0x02, 0xb9, 0xff, 0x70,
	0x9a, 0x57, 0x43, 0xfa, 0x6d, 0x17, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x81, 0x87, 0xdd, 0xcd,
	0xf2, 0x01, 0x00, 0x00,
}
