// Code generated by protoc-gen-go.
// source: proto/protocol.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	proto/protocol.proto

It has these top-level messages:
	Controller
	Vec3
	PlayerPosition
	MessageItem
	MessageContainer
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// MessageType определяет типы сообщений
type MessageType int32

const (
	MessageType_MsgController     MessageType = 0
	MessageType_MsgPlayerPosition MessageType = 1
)

var MessageType_name = map[int32]string{
	0: "MsgController",
	1: "MsgPlayerPosition",
}
var MessageType_value = map[string]int32{
	"MsgController":     0,
	"MsgPlayerPosition": 1,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Controller определяет клавиши управления
type Controller struct {
	MoveForward  bool                  `protobuf:"varint,1,opt,name=MoveForward" json:"MoveForward,omitempty"`
	MoveBackward bool                  `protobuf:"varint,2,opt,name=MoveBackward" json:"MoveBackward,omitempty"`
	MoveLeft     bool                  `protobuf:"varint,3,opt,name=MoveLeft" json:"MoveLeft,omitempty"`
	MoveRight    bool                  `protobuf:"varint,4,opt,name=MoveRight" json:"MoveRight,omitempty"`
	RotateLeft   bool                  `protobuf:"varint,5,opt,name=RotateLeft" json:"RotateLeft,omitempty"`
	RotateRight  bool                  `protobuf:"varint,6,opt,name=RotateRight" json:"RotateRight,omitempty"`
	Modifiers    *Controller_Modifiers `protobuf:"bytes,7,opt,name=modifiers" json:"modifiers,omitempty"`
}

func (m *Controller) Reset()                    { *m = Controller{} }
func (m *Controller) String() string            { return proto.CompactTextString(m) }
func (*Controller) ProtoMessage()               {}
func (*Controller) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Controller) GetModifiers() *Controller_Modifiers {
	if m != nil {
		return m.Modifiers
	}
	return nil
}

// Modifiers определяет клавиши-модификаторы
type Controller_Modifiers struct {
	Shift bool `protobuf:"varint,1,opt,name=Shift" json:"Shift,omitempty"`
	Ctrl  bool `protobuf:"varint,2,opt,name=Ctrl" json:"Ctrl,omitempty"`
	Alt   bool `protobuf:"varint,3,opt,name=Alt" json:"Alt,omitempty"`
	Meta  bool `protobuf:"varint,4,opt,name=Meta" json:"Meta,omitempty"`
}

func (m *Controller_Modifiers) Reset()                    { *m = Controller_Modifiers{} }
func (m *Controller_Modifiers) String() string            { return proto.CompactTextString(m) }
func (*Controller_Modifiers) ProtoMessage()               {}
func (*Controller_Modifiers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Vec3 struct {
	X float64 `protobuf:"fixed64,1,opt,name=X" json:"X,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=Y" json:"Y,omitempty"`
	Z float64 `protobuf:"fixed64,3,opt,name=Z" json:"Z,omitempty"`
}

func (m *Vec3) Reset()                    { *m = Vec3{} }
func (m *Vec3) String() string            { return proto.CompactTextString(m) }
func (*Vec3) ProtoMessage()               {}
func (*Vec3) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// PlayerPosition определяет позицию и движение игрока
type PlayerPosition struct {
	// Position определяет положение игрока
	Position *Vec3 `protobuf:"bytes,1,opt,name=Position" json:"Position,omitempty"`
	// Motion определяет движение игрока
	Motion *Vec3 `protobuf:"bytes,2,opt,name=Motion" json:"Motion,omitempty"`
	// Angle определяет направление игрока (угол между положительным направленим оси Y и направлением игрока по часовой стрелке)
	Angle float64 `protobuf:"fixed64,3,opt,name=Angle" json:"Angle,omitempty"`
	// Slew определяет поворот игрока
	Slew float64 `protobuf:"fixed64,4,opt,name=Slew" json:"Slew,omitempty"`
}

func (m *PlayerPosition) Reset()                    { *m = PlayerPosition{} }
func (m *PlayerPosition) String() string            { return proto.CompactTextString(m) }
func (*PlayerPosition) ProtoMessage()               {}
func (*PlayerPosition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PlayerPosition) GetPosition() *Vec3 {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *PlayerPosition) GetMotion() *Vec3 {
	if m != nil {
		return m.Motion
	}
	return nil
}

// MessageItem определяет одно сообщение
type MessageItem struct {
	Type MessageType `protobuf:"varint,1,opt,name=Type,enum=protocol.MessageType" json:"Type,omitempty"`
	Body []byte      `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
}

func (m *MessageItem) Reset()                    { *m = MessageItem{} }
func (m *MessageItem) String() string            { return proto.CompactTextString(m) }
func (*MessageItem) ProtoMessage()               {}
func (*MessageItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// MessageContainer определяет несколько сообщений
type MessageContainer struct {
	Messages []*MessageItem `protobuf:"bytes,1,rep,name=Messages" json:"Messages,omitempty"`
}

func (m *MessageContainer) Reset()                    { *m = MessageContainer{} }
func (m *MessageContainer) String() string            { return proto.CompactTextString(m) }
func (*MessageContainer) ProtoMessage()               {}
func (*MessageContainer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MessageContainer) GetMessages() []*MessageItem {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*Controller)(nil), "protocol.Controller")
	proto.RegisterType((*Controller_Modifiers)(nil), "protocol.Controller.Modifiers")
	proto.RegisterType((*Vec3)(nil), "protocol.Vec3")
	proto.RegisterType((*PlayerPosition)(nil), "protocol.PlayerPosition")
	proto.RegisterType((*MessageItem)(nil), "protocol.MessageItem")
	proto.RegisterType((*MessageContainer)(nil), "protocol.MessageContainer")
	proto.RegisterEnum("protocol.MessageType", MessageType_name, MessageType_value)
}

func init() { proto.RegisterFile("proto/protocol.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x51, 0xc1, 0x6a, 0xdb, 0x40,
	0x10, 0xed, 0xda, 0x8e, 0xab, 0x8c, 0x5c, 0xa3, 0x0c, 0x09, 0x88, 0x50, 0x82, 0xd0, 0xa1, 0xb8,
	0x39, 0xb8, 0xad, 0x73, 0xe8, 0xa5, 0x97, 0x24, 0xb4, 0x50, 0x88, 0x20, 0x6c, 0x4a, 0x49, 0xd2,
	0x93, 0x6a, 0xaf, 0x15, 0xd1, 0x8d, 0x36, 0xac, 0x96, 0x06, 0xff, 0x44, 0xff, 0xb3, 0x7f, 0x11,
	0x66, 0xb4, 0x92, 0x1c, 0xc8, 0x45, 0xbc, 0x37, 0xf3, 0xf6, 0xed, 0x7b, 0x5a, 0xd8, 0x7f, 0xb0,
	0xc6, 0x99, 0x0f, 0xfc, 0x5d, 0x1a, 0x3d, 0x67, 0x80, 0x41, 0xcb, 0xd3, 0xff, 0x03, 0x80, 0x73,
	0x53, 0x39, 0x6b, 0xb4, 0x56, 0x16, 0x13, 0x08, 0x33, 0xf3, 0x57, 0x7d, 0x33, 0xf6, 0x31, 0xb7,
	0xab, 0x58, 0x24, 0x62, 0x16, 0xc8, 0xed, 0x11, 0xa6, 0x30, 0x21, 0x7a, 0x96, 0x2f, 0xff, 0xb0,
	0x64, 0xc0, 0x92, 0x67, 0x33, 0x3c, 0x84, 0x80, 0xf8, 0x85, 0x5a, 0xbb, 0x78, 0xc8, 0xfb, 0x8e,
	0xe3, 0x5b, 0xd8, 0x25, 0x2c, 0xcb, 0xe2, 0xce, 0xc5, 0x23, 0x5e, 0xf6, 0x03, 0x3c, 0x02, 0x90,
	0xc6, 0xe5, 0xae, 0x39, 0xbb, 0xc3, 0xeb, 0xad, 0x09, 0xe5, 0x6b, 0x58, 0x73, 0x7e, 0xdc, 0xe4,
	0xdb, 0x1a, 0xe1, 0x17, 0xd8, 0xbd, 0x37, 0xab, 0x72, 0x5d, 0x2a, 0x5b, 0xc7, 0xaf, 0x13, 0x31,
	0x0b, 0x17, 0x47, 0xf3, 0xae, 0x7e, 0x5f, 0x75, 0x9e, 0xb5, 0x2a, 0xd9, 0x1f, 0x38, 0xfc, 0x45,
	0xe9, 0x3c, 0xc1, 0x7d, 0xd8, 0xb9, 0xba, 0x2b, 0xd7, 0xce, 0xff, 0x86, 0x86, 0x20, 0xc2, 0xe8,
	0xdc, 0x59, 0xed, 0x8b, 0x33, 0xc6, 0x08, 0x86, 0xa7, 0xba, 0xed, 0x4a, 0x90, 0x54, 0x99, 0x72,
	0xb9, 0x6f, 0xc8, 0x38, 0xfd, 0x08, 0xa3, 0x9f, 0x6a, 0x79, 0x82, 0x13, 0x10, 0xd7, 0xec, 0x29,
	0xa4, 0xb8, 0x26, 0x76, 0xc3, 0x66, 0x42, 0x8a, 0x1b, 0x62, 0xb7, 0xec, 0x23, 0xa4, 0xb8, 0x4d,
	0xff, 0x09, 0x98, 0x5e, 0xea, 0x7c, 0xa3, 0xec, 0xa5, 0xa9, 0x4b, 0x57, 0x9a, 0x0a, 0x8f, 0x21,
	0x68, 0x31, 0x7b, 0x84, 0x8b, 0x69, 0x5f, 0x8f, 0xec, 0x65, 0xb7, 0xc7, 0x77, 0x30, 0xce, 0x0c,
	0x2b, 0x07, 0x2f, 0x2a, 0xfd, 0x96, 0x8a, 0x9e, 0x56, 0x85, 0x56, 0xfe, 0xe2, 0x86, 0x50, 0x85,
	0x2b, 0xad, 0x1e, 0xb9, 0x82, 0x90, 0x8c, 0xd3, 0x0b, 0x08, 0x33, 0x55, 0xd7, 0x79, 0xa1, 0xbe,
	0x3b, 0x75, 0x8f, 0xef, 0x61, 0xf4, 0x63, 0xf3, 0xa0, 0x38, 0xc8, 0x74, 0x71, 0xd0, 0xdb, 0x7b,
	0x11, 0x2d, 0x25, 0x4b, 0xc8, 0xed, 0xcc, 0xac, 0x36, 0x9c, 0x64, 0x22, 0x19, 0xa7, 0x5f, 0x21,
	0xf2, 0x42, 0x7a, 0x97, 0xbc, 0xac, 0x94, 0xc5, 0x4f, 0x10, 0xf8, 0x59, 0x1d, 0x8b, 0x64, 0x38,
	0x0b, 0x5f, 0xb0, 0xa5, 0xbb, 0x65, 0x27, 0x3b, 0xfe, 0xdc, 0x85, 0xe2, 0x9b, 0xf6, 0xe0, 0x4d,
	0x56, 0x17, 0xfd, 0x4b, 0x47, 0xaf, 0xf0, 0x00, 0xf6, 0xb2, 0xba, 0x78, 0xfe, 0x27, 0x23, 0xf1,
	0x7b, 0xcc, 0xc6, 0x27, 0x4f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x05, 0x31, 0x20, 0xc0, 0x25, 0x03,
	0x00, 0x00,
}
