// Code generated by protoc-gen-go.
// source: proto/protocol.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	proto/protocol.proto

It has these top-level messages:
	MessageItem
	MessageContainer
	Controller
	Vec3
	PlayerPosition
	Terrain
	Chunk
	ChunkRequest
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// MessageType определяет типы сообщений
type MessageType int32

const (
	MessageType_MsgController     MessageType = 0
	MessageType_MsgPlayerPosition MessageType = 1
	MessageType_MsgTerrain        MessageType = 2
	MessageType_MsgChunk          MessageType = 3
	MessageType_MsgChunkRequest   MessageType = 4
)

var MessageType_name = map[int32]string{
	0: "MsgController",
	1: "MsgPlayerPosition",
	2: "MsgTerrain",
	3: "MsgChunk",
	4: "MsgChunkRequest",
}
var MessageType_value = map[string]int32{
	"MsgController":     0,
	"MsgPlayerPosition": 1,
	"MsgTerrain":        2,
	"MsgChunk":          3,
	"MsgChunkRequest":   4,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// MessageItem определяет одно сообщение
type MessageItem struct {
	Type MessageType `protobuf:"varint,1,opt,name=Type,enum=protocol.MessageType" json:"Type,omitempty"`
	Body []byte      `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
}

func (m *MessageItem) Reset()                    { *m = MessageItem{} }
func (m *MessageItem) String() string            { return proto.CompactTextString(m) }
func (*MessageItem) ProtoMessage()               {}
func (*MessageItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// MessageContainer определяет несколько сообщений
type MessageContainer struct {
	Messages []*MessageItem `protobuf:"bytes,1,rep,name=Messages" json:"Messages,omitempty"`
}

func (m *MessageContainer) Reset()                    { *m = MessageContainer{} }
func (m *MessageContainer) String() string            { return proto.CompactTextString(m) }
func (*MessageContainer) ProtoMessage()               {}
func (*MessageContainer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MessageContainer) GetMessages() []*MessageItem {
	if m != nil {
		return m.Messages
	}
	return nil
}

// Controller определяет клавиши управления
type Controller struct {
	MoveForward  bool                  `protobuf:"varint,1,opt,name=MoveForward" json:"MoveForward,omitempty"`
	MoveBackward bool                  `protobuf:"varint,2,opt,name=MoveBackward" json:"MoveBackward,omitempty"`
	MoveLeft     bool                  `protobuf:"varint,3,opt,name=MoveLeft" json:"MoveLeft,omitempty"`
	MoveRight    bool                  `protobuf:"varint,4,opt,name=MoveRight" json:"MoveRight,omitempty"`
	RotateLeft   bool                  `protobuf:"varint,5,opt,name=RotateLeft" json:"RotateLeft,omitempty"`
	RotateRight  bool                  `protobuf:"varint,6,opt,name=RotateRight" json:"RotateRight,omitempty"`
	Mods         *Controller_Modifiers `protobuf:"bytes,7,opt,name=Mods" json:"Mods,omitempty"`
}

func (m *Controller) Reset()                    { *m = Controller{} }
func (m *Controller) String() string            { return proto.CompactTextString(m) }
func (*Controller) ProtoMessage()               {}
func (*Controller) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Controller) GetMods() *Controller_Modifiers {
	if m != nil {
		return m.Mods
	}
	return nil
}

// Modifiers определяет клавиши-модификаторы
type Controller_Modifiers struct {
	Shift bool `protobuf:"varint,1,opt,name=Shift" json:"Shift,omitempty"`
	Ctrl  bool `protobuf:"varint,2,opt,name=Ctrl" json:"Ctrl,omitempty"`
	Alt   bool `protobuf:"varint,3,opt,name=Alt" json:"Alt,omitempty"`
	Meta  bool `protobuf:"varint,4,opt,name=Meta" json:"Meta,omitempty"`
}

func (m *Controller_Modifiers) Reset()                    { *m = Controller_Modifiers{} }
func (m *Controller_Modifiers) String() string            { return proto.CompactTextString(m) }
func (*Controller_Modifiers) ProtoMessage()               {}
func (*Controller_Modifiers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type Vec3 struct {
	X float64 `protobuf:"fixed64,1,opt,name=X" json:"X,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=Y" json:"Y,omitempty"`
	Z float64 `protobuf:"fixed64,3,opt,name=Z" json:"Z,omitempty"`
}

func (m *Vec3) Reset()                    { *m = Vec3{} }
func (m *Vec3) String() string            { return proto.CompactTextString(m) }
func (*Vec3) ProtoMessage()               {}
func (*Vec3) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// PlayerPosition определяет позицию и движение игрока
type PlayerPosition struct {
	// Position определяет положение игрока
	Position *Vec3 `protobuf:"bytes,1,opt,name=Position" json:"Position,omitempty"`
	// Motion определяет движение игрока
	Motion *Vec3 `protobuf:"bytes,2,opt,name=Motion" json:"Motion,omitempty"`
	// Angle определяет направление игрока (угол между положительным направленим оси Y и направлением игрока по часовой стрелке)
	Angle float64 `protobuf:"fixed64,3,opt,name=Angle" json:"Angle,omitempty"`
	// Slew определяет поворот игрока
	Slew float64 `protobuf:"fixed64,4,opt,name=Slew" json:"Slew,omitempty"`
}

func (m *PlayerPosition) Reset()                    { *m = PlayerPosition{} }
func (m *PlayerPosition) String() string            { return proto.CompactTextString(m) }
func (*PlayerPosition) ProtoMessage()               {}
func (*PlayerPosition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PlayerPosition) GetPosition() *Vec3 {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *PlayerPosition) GetMotion() *Vec3 {
	if m != nil {
		return m.Motion
	}
	return nil
}

// Terrain определяет карту
type Terrain struct {
	// Width определяет ширину
	Width int32 `protobuf:"varint,1,opt,name=Width" json:"Width,omitempty"`
	// Height определяет высоту
	Height int32 `protobuf:"varint,2,opt,name=Height" json:"Height,omitempty"`
	// Seed определяет зерно генератора
	Seed int64 `protobuf:"varint,3,opt,name=Seed" json:"Seed,omitempty"`
	// ChunkSize определяет размер чанка
	ChunkSize int32 `protobuf:"varint,4,opt,name=ChunkSize" json:"ChunkSize,omitempty"`
}

func (m *Terrain) Reset()                    { *m = Terrain{} }
func (m *Terrain) String() string            { return proto.CompactTextString(m) }
func (*Terrain) ProtoMessage()               {}
func (*Terrain) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// Chunk определяет чанк карты
type Chunk struct {
	// Index определяет индекс чанка
	Index int32 `protobuf:"varint,1,opt,name=Index" json:"Index,omitempty"`
	// Map определяет карту
	Map []*Chunk_Tile `protobuf:"bytes,2,rep,name=Map" json:"Map,omitempty"`
}

func (m *Chunk) Reset()                    { *m = Chunk{} }
func (m *Chunk) String() string            { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()               {}
func (*Chunk) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Chunk) GetMap() []*Chunk_Tile {
	if m != nil {
		return m.Map
	}
	return nil
}

// Tile определяет тайл карты
type Chunk_Tile struct {
	Ground int32 `protobuf:"varint,1,opt,name=Ground" json:"Ground,omitempty"`
	Block  int32 `protobuf:"varint,2,opt,name=Block" json:"Block,omitempty"`
	Detail int32 `protobuf:"varint,3,opt,name=Detail" json:"Detail,omitempty"`
}

func (m *Chunk_Tile) Reset()                    { *m = Chunk_Tile{} }
func (m *Chunk_Tile) String() string            { return proto.CompactTextString(m) }
func (*Chunk_Tile) ProtoMessage()               {}
func (*Chunk_Tile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

// ChunkRequest определяет список необходимых чанков
type ChunkRequest struct {
	Chunks []int32 `protobuf:"varint,1,rep,packed,name=Chunks" json:"Chunks,omitempty"`
}

func (m *ChunkRequest) Reset()                    { *m = ChunkRequest{} }
func (m *ChunkRequest) String() string            { return proto.CompactTextString(m) }
func (*ChunkRequest) ProtoMessage()               {}
func (*ChunkRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*MessageItem)(nil), "protocol.MessageItem")
	proto.RegisterType((*MessageContainer)(nil), "protocol.MessageContainer")
	proto.RegisterType((*Controller)(nil), "protocol.Controller")
	proto.RegisterType((*Controller_Modifiers)(nil), "protocol.Controller.Modifiers")
	proto.RegisterType((*Vec3)(nil), "protocol.Vec3")
	proto.RegisterType((*PlayerPosition)(nil), "protocol.PlayerPosition")
	proto.RegisterType((*Terrain)(nil), "protocol.Terrain")
	proto.RegisterType((*Chunk)(nil), "protocol.Chunk")
	proto.RegisterType((*Chunk_Tile)(nil), "protocol.Chunk.Tile")
	proto.RegisterType((*ChunkRequest)(nil), "protocol.ChunkRequest")
	proto.RegisterEnum("protocol.MessageType", MessageType_name, MessageType_value)
}

func init() { proto.RegisterFile("proto/protocol.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 599 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x53, 0xcd, 0x4e, 0xdb, 0x40,
	0x10, 0xee, 0x3a, 0x76, 0x48, 0x27, 0x69, 0x6a, 0xb6, 0x50, 0x59, 0xa8, 0x42, 0x91, 0x0f, 0x28,
	0xe5, 0x90, 0xb6, 0xe1, 0x09, 0x80, 0xfe, 0x21, 0x61, 0x09, 0x2d, 0xa8, 0x05, 0x7a, 0x72, 0xe3,
	0x21, 0xd9, 0xe2, 0x7a, 0xa9, 0xbd, 0x94, 0xa6, 0x0f, 0xd1, 0x4b, 0x1f, 0xb0, 0xaf, 0x52, 0xcd,
	0x78, 0x13, 0x07, 0x89, 0x8b, 0x35, 0xdf, 0xcc, 0x37, 0xdf, 0xcc, 0xe7, 0xdd, 0x85, 0x8d, 0x9b,
	0xd2, 0x58, 0xf3, 0x8a, 0xbf, 0x13, 0x93, 0x8f, 0x38, 0x90, 0x9d, 0x05, 0x8e, 0x8f, 0xa1, 0x9b,
	0x60, 0x55, 0xa5, 0x53, 0x3c, 0xb2, 0xf8, 0x5d, 0xbe, 0x04, 0xff, 0x6c, 0x7e, 0x83, 0x91, 0x18,
	0x88, 0x61, 0x7f, 0xbc, 0x39, 0x5a, 0xf6, 0x39, 0x12, 0x15, 0x15, 0x53, 0xa4, 0x04, 0xff, 0xc0,
	0x64, 0xf3, 0xc8, 0x1b, 0x88, 0x61, 0x4f, 0x71, 0x1c, 0xbf, 0x83, 0xd0, 0x11, 0x0f, 0x4d, 0x61,
	0x53, 0x5d, 0x60, 0x29, 0xdf, 0x40, 0xc7, 0xe5, 0xaa, 0x48, 0x0c, 0x5a, 0xc3, 0xee, 0x03, 0xb2,
	0x34, 0x5b, 0x2d, 0x69, 0xf1, 0x3f, 0x0f, 0x80, 0x04, 0x4a, 0x93, 0xe7, 0x58, 0xca, 0x01, 0x74,
	0x13, 0xf3, 0x13, 0xdf, 0x9b, 0xf2, 0x2e, 0x2d, 0x33, 0xde, 0xad, 0xa3, 0x56, 0x53, 0x32, 0x86,
	0x1e, 0xc1, 0x83, 0x74, 0x72, 0xcd, 0x14, 0x8f, 0x29, 0xf7, 0x72, 0x72, 0x0b, 0x3a, 0x84, 0x8f,
	0xf1, 0xca, 0x46, 0x2d, 0xae, 0x2f, 0xb1, 0x7c, 0x01, 0x8f, 0x29, 0x56, 0x7a, 0x3a, 0xb3, 0x91,
	0xcf, 0xc5, 0x26, 0x21, 0xb7, 0x01, 0x94, 0xb1, 0xa9, 0xad, 0x7b, 0x03, 0x2e, 0xaf, 0x64, 0x68,
	0xbf, 0x1a, 0xd5, 0xfd, 0xed, 0x7a, 0xbf, 0x95, 0x94, 0x1c, 0x83, 0x9f, 0x98, 0xac, 0x8a, 0xd6,
	0x06, 0x62, 0xd8, 0x1d, 0x6f, 0x37, 0xfe, 0x1b, 0x97, 0xa3, 0xc4, 0x64, 0xfa, 0x4a, 0x63, 0x59,
	0x29, 0xe6, 0x6e, 0x7d, 0xa1, 0x9d, 0x5c, 0x4a, 0x6e, 0x40, 0x70, 0x3a, 0xd3, 0x57, 0xd6, 0x99,
	0xaf, 0x01, 0x1d, 0xc1, 0xa1, 0x2d, 0x73, 0x67, 0x97, 0x63, 0x19, 0x42, 0x6b, 0x3f, 0x5f, 0x38,
	0xa4, 0x90, 0x58, 0x09, 0xda, 0xd4, 0xf9, 0xe2, 0x38, 0x7e, 0x0d, 0xfe, 0x27, 0x9c, 0xec, 0xc9,
	0x1e, 0x88, 0x73, 0xd6, 0x14, 0x4a, 0x9c, 0x13, 0xba, 0x60, 0x31, 0xa1, 0xc4, 0x05, 0xa1, 0x4b,
	0xd6, 0x11, 0x4a, 0x5c, 0xc6, 0x7f, 0x04, 0xf4, 0x4f, 0xf2, 0x74, 0x8e, 0xe5, 0x89, 0xa9, 0xb4,
	0xd5, 0xa6, 0x90, 0xbb, 0xd0, 0x59, 0xc4, 0xac, 0xd1, 0x1d, 0xf7, 0x1b, 0x67, 0x24, 0xaf, 0x96,
	0x75, 0xb9, 0x03, 0xed, 0xc4, 0x30, 0xd3, 0x7b, 0x90, 0xe9, 0xaa, 0x64, 0x74, 0xbf, 0x98, 0xe6,
	0xe8, 0x06, 0xd7, 0x80, 0x2c, 0x9c, 0xe6, 0x78, 0xc7, 0x16, 0x84, 0xe2, 0x38, 0xd6, 0xb0, 0x76,
	0x86, 0x65, 0x99, 0x6a, 0x6e, 0xfa, 0xac, 0x33, 0x3b, 0xe3, 0x2d, 0x02, 0x55, 0x03, 0xf9, 0x1c,
	0xda, 0x1f, 0x91, 0x4f, 0xc4, 0xe3, 0xb4, 0x43, 0x2c, 0x86, 0x98, 0xf1, 0x84, 0x96, 0xe2, 0x98,
	0x2e, 0xc0, 0xe1, 0xec, 0xb6, 0xb8, 0x3e, 0xd5, 0xbf, 0x91, 0xa7, 0x04, 0xaa, 0x49, 0xc4, 0x7f,
	0x05, 0x04, 0x8c, 0x68, 0xd2, 0x51, 0x91, 0xe1, 0xaf, 0xc5, 0x24, 0x06, 0x72, 0x07, 0x5a, 0x49,
	0x7a, 0x13, 0x79, 0x7c, 0xbb, 0x37, 0x56, 0x4e, 0x97, 0x7a, 0x46, 0x67, 0x3a, 0x47, 0x45, 0x84,
	0xad, 0x63, 0xf0, 0x09, 0xd0, 0x66, 0x1f, 0x4a, 0x73, 0x5b, 0x64, 0x4e, 0xc6, 0x21, 0x52, 0x3f,
	0xc8, 0xcd, 0xe4, 0xda, 0x2d, 0x5c, 0x03, 0x62, 0xbf, 0x45, 0x9b, 0xea, 0x9c, 0x37, 0x0e, 0x94,
	0x43, 0xf1, 0x0e, 0xf4, 0x78, 0x80, 0xc2, 0x1f, 0xb7, 0x58, 0x59, 0xe2, 0x31, 0xae, 0x9f, 0x59,
	0xa0, 0x1c, 0xda, 0xfd, 0xb6, 0x7c, 0xe2, 0xfc, 0x6e, 0xd7, 0xe1, 0x49, 0x52, 0x4d, 0x9b, 0x8b,
	0x17, 0x3e, 0x92, 0x9b, 0xb0, 0x9e, 0x54, 0xd3, 0xfb, 0xa7, 0x1b, 0x0a, 0xd9, 0x07, 0x48, 0xaa,
	0xa9, 0xfb, 0xc9, 0xa1, 0x27, 0x7b, 0xd0, 0xa1, 0x4e, 0x52, 0x0d, 0x5b, 0xf2, 0x19, 0x3c, 0x5d,
	0x20, 0xb7, 0x41, 0xe8, 0x7f, 0x6d, 0xb3, 0xf7, 0xbd, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc4,
	0x1c, 0x53, 0x3e, 0x77, 0x04, 0x00, 0x00,
}
